FROM ubuntu:24.04

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -yqq update

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -yqq install \
      --no-install-recommends \
      ca-certificates \
      cmake \
      curl \
      file \
      g++ \
      gcc \
      gfortran \
      git \
      hdf5-filter-plugin-blosc-serial \
      ksh \
      libblas-dev \
      libeccodes-dev \
      libfyaml-dev \
      libhdf5-dev \
      liblapack-dev \
      libnetcdf-dev \
      libnetcdff-dev \
      libopenmpi-dev \
      libxml2-dev \
      make \
      perl \
      python-is-python3 \
      python3-dev \
      python3-jinja2 \
      python3-pip \
      python3-six \
      python3-venv \
      rsync \
      ssh \
      vim \
      sqlite3 \
      build-essential \
      openssh-client \
      sudo \
 && rm -rf /var/lib/apt/lists/*

# Enable oversubscription when running mpiexec from OpenMPI:
ENV OMPI_MCA_rmaps_base_oversubscribe=1

RUN useradd --create-home --home-dir /home/icon --shell /bin/bash --groups sudo icon \
 && echo '%icon ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER icon
WORKDIR /home/icon

RUN curl -fsSL https://opencode.ai/install | bash
ENV PATH="/home/icon/.opencode/bin:${PATH}"

RUN echo 'export PS1="\[$(tput bold)\]\[$(tput setaf 2)\]\u@\[$(tput setaf 3)\]container\[$(tput sgr0)\]:\w$ "' >> ~/.bashrc